---
title: "Epsilon Volume"
output: html_notebook
---

```{r load_functions}
library(tidyverse)
library(rstan)
library(Rfast)
source("../../SampleStiefelUniformQr.R")
source("../../givens.R")

get_longitudinal_indices <- function(n, p) {
  idx <- 1
  indices <- c()
  for(i in 1:p) {
    for(j in (i+1):n) {
      if(j > i+1) {
        indices <- c(indices, idx)
      }
      idx <- idx + 1
    }
  }
  
  indices
}

random_stiefel_angles <- function(n, p, sample_id) {
  SampleStiefelUniformQr(n,p) %>%
    SampleStiefelUniformQr(n,p) %>%
    GivensTransform()
}

random_stiefel_longitudinal <- function(n, p, sample_id) {
  draw <-
    SampleStiefelUniformQr(n,p) %>%
    GivensTransform()
  
  draw[get_longitudinal_indices(n,p)]
}

any_angle_in_patch <- function(angles, eps) {
  any(abs(angles) > (pi/2 - eps))
}

random_stiefel_in_patch <- function(n, p, sample_id) {
  draw <- random_stiefel_longitudinal(n, p)
  
  eps <- c(0.1, 0.05, 0.025, 0.0125, 1e-5)
  outer(abs(draw), eps,
        FUN = function(x, y) x > (pi/2-y)) %>%
    apply(2, any) %>%
    matrix(nrow = 1) %>%
    as_tibble %>%
    set_names(as.character(eps)) %>%
    mutate(sample_id = sample_id)
}

get_stats <- function(sample_mat) {
  theta_13 <- 
    sample_mat %>%
    apply(1, function(x) GivensTransform(matrix(x, ncol = 1))[2])

  princ_angle <-
    sample_mat %>%
    apply(1, function(x) acos(sum(x*c(0,0,1))))
  
  n <- nrow(sample_mat)
  p <- ncol(sample_mat)
  
  eps_1 <- (abs(theta_13) > (pi/2 - 1e-1))
  eps_2 <- (abs(theta_13) > (pi/2 - 1e-1/2))
  eps_3 <- (abs(theta_13) > (pi/2 - 1e-1/4))
  eps_4 <- (abs(theta_13) > (pi/2 - 1e-1/8))
  eps_5 <- (abs(theta_13) > (pi/2 - 1e-5))
  
  tibble(theta_13_s = theta_13,
         princ_angle_s = princ_angle,
         eps_1 = eps_1,
         eps_2 = eps_2,
         eps_3 = eps_3,
         eps_4 = eps_4,
         eps_5 = eps_5)
}
```

# Table Showing Probabilities of Being in Patch for QR Trick

```{r}
settings <-
  expand.grid(n = c(10, 20, 50),
            p = c(1, 3, 10),
            sample_id = 1:1e5) %>%
  as_tibble()

raw_long_samples <- pmap(settings, random_stiefel_longitudinal)

eps_1 <- map_lgl(raw_long_samples, any_angle_in_patch, eps = 1e-1)
eps_2 <- map_lgl(raw_long_samples, any_angle_in_patch, eps = 1e-1/2)
eps_3 <- map_lgl(raw_long_samples, any_angle_in_patch, eps = 1e-1/4)
eps_4 <- map_lgl(raw_long_samples, any_angle_in_patch, eps = 1e-1/8)
eps_5 <- map_lgl(raw_long_samples, any_angle_in_patch, eps = 1e-5)

in_patch <-
  settings %>%
  mutate(eps_1 = eps_1,
         eps_2 = eps_2,
         eps_3 = eps_3,
         eps_4 = eps_4,
         eps_5 = eps_5)

in_patch %>%
  group_by(n, p) %>%
  summarize(pr_1 = mean(eps_1),
            pr_2 = mean(eps_2),
            pr_3 = mean(eps_3),
            pr_4 = mean(eps_4),
            pr_5 = mean(eps_5)) %>%
  arrange(p, n)
```


```{r}
n <- 3
mu <- c(0, 0, 1)
kappa <- 10.0
EPS <- 1e-5

vmf_settings <-
  expand.grid(theta_12 = c(0.0),
            theta_13 = c(pi/2),
            kappa = c(1e0, 1e1, 1e2, 1e3)) %>%
  as_tibble

vmf_raw_samples <-
  vmf_settings %>%
  pmap(function(theta_12, theta_13, kappa) {
        m <- InverseGivensTransform(c(theta_12, theta_13), 3, 1)
        rvmf(1e5, m, kappa)
    })

vmf_summary_stats <- vmf_raw_samples %>% map(get_stats)

vmf_samples <-
  map2(vmf_summary_stats, 1:length(vmf_summary_stats),
     function(df, i) df %>% mutate(settings_id = i)) %>%
  bind_rows() %>%
  inner_join(vmf_settings %>% mutate(settings_id = row_number())) %>%
  mutate(sample = "VMF")

vmf_samples %>%
  ggplot(aes(princ_angle_s)) +
  geom_histogram(binwidth = 0.01) +
  facet_grid(kappa ~ theta_13)

vmf_samples %>%
  group_by(kappa) %>%
  summarize(pr_1 = mean(eps_1),
            pr_2 = mean(eps_2),
            pr_3 = mean(eps_3),
            pr_4 = mean(eps_4),
            pr_5 = mean(eps_5))
```

```{r sample_givens}
vmf_stan_settings <-
  expand.grid(EPS = c(0.1, 0.05, 0.025, 0.0125, 1e-5),
            kappa = c(1e0, 1e1, 1e2, 1e3)) %>%
  as_tibble

run_stan_fit_get_samples <- function(EPS, kappa) {
  print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
  print(kappa)
  print(EPS)
  fit <- stan("../../Stan/new_khatri/fisher_von_mises_givens.stan",
       data = list(n = n, mu = c(0, 0, 1), kappa = kappa, EPS = EPS),
       chains = 1, iter = 2e5)
  
  tibble(princ_angle_s = extract(fit)$theta_princ) %>%
    mutate(EPS = EPS, kappa = kappa)
}

vmf_stan_samples <-
  vmf_stan_settings %>%
  pmap(run_stan_fit_get_samples) %>%
  bind_rows() %>%
  mutate(sample = "Stan")

saveRDS(vmf_stan_samples, file = "../../vmf_stan_samples.rds")
```

```{r}
library(latex2exp)

all_samples <- 
  vmf_samples %>%
  select(sample, kappa, princ_angle_s) %>%
  mutate(EPS = "Ford") %>%
  bind_rows(vmf_stan_samples %>% mutate(EPS = as.character(EPS))) %>%
  mutate(EPS = factor(EPS, levels = c("0.1", "0.05", "0.025", "0.0125", "1e-05", "Ford")))

all_samples %>%
  group_by(EPS, kappa) %>%
  summarize(m = round(mean(princ_angle_s), 4),
            s = round(mean(princ_angle_s^2), 4)) %>%
  arrange(kappa, EPS)

all_samples %>%
  ggplot(aes(princ_angle_s)) +
  geom_histogram(binwidth = 0.01) +
  facet_grid(EPS ~ kappa, scales = "free") +
  theme_bw() +
  xlab("Principal Angle")
```

```{r}
fit_12 <- stan("../../Stan/new_khatri/fisher_von_mises_givens.stan",
            data = list(n = 3, mu = c(0, 0, 1), kappa = 1e14, EPS = 0.0),
            chains = 1, iter = 1e5 + 1000, warmup = 1000)

s <- extract(fit_12)
fit_12_samples <- tibble(princ_angle_s = s$theta_princ, sample = "1e12")

fit_15 <- stan("../../Stan/new_khatri/fisher_von_mises_givens.stan",
            data = list(n = 3, mu = c(0, 0, 1), kappa = 1e15, EPS = 0.0),
            chains = 1, iter = 1e5 + 10000, warmup = 10000)

s <- extract(fit_15)
fit_15_samples <- tibble(princ_angle_s = s$theta_princ, sample = "1e15")

n <- 3
mu <- c(0, 0, 1)
kappa <- 1e15
EPS <- 1e-5

vmf_settings <-
  expand.grid(theta_12 = c(0.0),
            theta_13 = c(pi/2),
            kappa = c(1e15)) %>%
  as_tibble

vmf_raw_samples <-
  vmf_settings %>%
  pmap(function(theta_12, theta_13, kappa) {
        m <- InverseGivensTransform(c(theta_12, theta_13), 3, 1)
        rvmf(1e5, m, kappa)
    })

vmf_summary_stats <- vmf_raw_samples %>% map(get_stats)

vmf_samples <-
  map2(vmf_summary_stats, 1:length(vmf_summary_stats),
     function(df, i) df %>% mutate(settings_id = i)) %>%
  bind_rows() %>%
  inner_join(vmf_settings %>% mutate(settings_id = row_number())) %>%
  mutate(sample = "VMF") %>%
  select(princ_angle_s, sample)

all_samples_high_kappa <-
  bind_rows(fit_12_samples) %>%
  bind_rows(fit_15_samples)

all_samples_high_kappa %>% ggplot(aes(princ_angle_s)) + geom_histogram() + facet_grid(sample ~ .)
```

```{r}
fit <-
  stan("../../Stan/new_khatri/givens_uniform_patch.stan",
            data = list(n = 3, p = 1, EPS = 0.0),
            chains = 1, iter = 1e5 + 1000, warmup = 1000)

s <- extract(fit)

g <- unconstrain_pars(fit, list(x_lon = array(1.0), y_lon = array(0.0), theta_lat = array(pi/2 - 1e-8)))
grad_log_prob(fit, g)

fit <-
  stan("../../Stan/new_khatri/grad_tester.stan",
            data = list(n = 3, p = 1, EPS = 0.0),
            chains = 1, iter = 1e3, init = list(list(theta = 0.0)))
```

