---
title: "PPCA Sparse"
output: html_notebook
---

```{r load_functions}
library(rstan)
library(tidyverse)
library(reshape2)
source("../../givens.R")

draw_uniform_stiefel <- function(n, p) {
  Y_raw <- matrix(rnorm(n*p), nrow = n, ncol = p)
  Y <- qr(Y_raw) %>% qr.Q()
  
  Y
}

# get PPCA max-lik estimate from sample covariance matrix
get_W_ml <- function(S, n, p) {
  eig <- eigen(S)
  
  sigma_sq_ml <- 1/(n-p) * sum(eig$values[(p+1):n])
  
  U_q <- eig$vector[, 1:p]
  Lambda_q <- diag(eig$values[1:p])
  W_ml <- U_q %*% sqrt(Lambda_q - sigma_sq_ml*diag(p))
  
  W_ml
}
```

```{r generate_data}
n <- 50
p <- 3
N <- 100

lambda_sq <- c(5.0, 3.0, 1.5)
sigma_sq <- 1.0

W <- draw_uniform_stiefel(50, 3)
theta <- GivensTransform(W)
theta_sparse <- theta * rbinom(length(theta), 1, 0.2)
W_sparse <- InverseGivensTransform(theta_sparse, n, p)

data <-
  GenerateHighDimData(n = n, p = p, W = W_sparse,
                      LambdaVec = sqrt(lambda_sq),
                      sd = sigma_sq,
                      N = N)

data$W <- W_sparse

saveRDS(data, "ppca_sparse_data.RDS")
# data <- readRDS("ppca_sparse_data.RDS")
```

```{r, message=FALSE}
x <- data$x
x_matrix <- as.matrix(x)
Sigma_hat <- (1/N)*t(x_matrix) %*% x_matrix
Y_ml <- eigen(Sigma_hat)$vector[,1:p]

for(i in 1:p) {
  qTv <- sum(Y_ml[,i]*W_sparse[,i])
  if(qTv < 0.0) {
    Y_ml[,i] <- -Y_ml[,i]
  }
}

dat <- list(n = n, p = p, N = N, SigmaHat = Sigma_hat, Y_ml = Y_ml)
fit_non_sparse <- stan(file = "../../Stan/new_khatri/ppca_patch_with_mirror_new.stan",
            data = dat, chains = 1, iter = 1e4, refresh = 1000)
```

```{r}
# NOT USING ANYMORE
# s <- extract(fit)
# 
# W_sparse_melted <-
#   W_sparse %>%
#   melt() %>%
#   set_names("row", "col", "true_value")
# 
# s_W <- extract(fit)$Y
# W_quantiles <-
#   s_W %>%
#   melt() %>%
#   as_tibble %>%
#   set_names("sample_id", "row", "col", "value") %>%
#   group_by(row, col) %>%
#   summarize(Q10 = quantile(value, 0.1),
#             Q50 = quantile(value, 0.5),
#             Q90 = quantile(value, 0.9)) %>%
#   ungroup() %>%
#   inner_join(W_sparse_melted) %>%
#   filter(col <= 3, row <= 10) %>%
#   mutate(in_interval = Q10 <= true_value & true_value < Q90)
# 
# W_quantiles %>%
#   mutate(idx = row_number()) %>%
#   ggplot() +
#   geom_errorbar(aes(idx, ymin = Q10, ymax = Q90)) +
#   geom_point(aes(idx, true_value), color = "red")
```

```{r}
sample_horseshoe <- function(tau0, nu, s) {
  tau <- tau0 * abs(rcauchy(1))
  c_sq <- 1/rgamma(1, shape = nu/2, scale = nu*s^2/2)
  c <- sqrt(c_sq)
  
  lambda <- abs(rcauchy(1))
  lambda_tilde <- c*lambda / sqrt(c_sq + tau^2*lambda^2)
  
  beta <- rnorm(1, sd = tau*lambda_tilde)
  
  beta
}

1:1000 %>%
  map(function(i) sample_horseshoe(0.01, 10, pi/4)) %>%
  unlist() %>% 
  qplot
```
```{r}
dat_horseshoe <- c(dat, list(tau0 = 0.01, nu = 10, s = pi/4))
fit <- stan(file = "../../Stan/ppca_horseshoe.stan",
            data = dat_horseshoe, chains = 1, iter = 1e4, refresh = 100)

s <- extract(fit)

print(fit_non_sparse, pars = c("lambda_sq", "sigmaSq"))
print(fit_mirror, pars = c("lambda_sq", "sigmaSq"))

s$Y_sparsity %>% qplot
```

```{r}
s_nonsparse <- extract(fit_non_sparse)
s <- extract(fit)

q_Y_tibble <-
  cbind(s$Y_mirrored[,,1], s$Y_mirrored[,,2],s$Y_mirrored[,,3]) %>%
  melt() %>%
  as_tibble() %>%
  set_names(c("sample_id", "var_id", "value")) %>%
  group_by(var_id) %>%
  summarize(Q10 = quantile(value, 0.1),
            Q90 = quantile(value, 0.9)) %>%
  mutate(true_value = as.vector(W_sparse)) %>%
  arrange(true_value) %>%
  mutate(var_id = row_number()) %>%
  mutate(covered = Q10 <= true_value & true_value <= Q90) %>%
  mutate(model = "Sparse")

q_Y_tibble_sparse <-
  cbind(s_nonsparse$Y_mirrored[,,1], s_nonsparse$Y_mirrored[,,2], s_nonsparse$Y_mirrored[,,3]) %>%
  melt() %>%
  as_tibble() %>%
  set_names(c("sample_id", "var_id", "value")) %>%
  group_by(var_id) %>%
  summarize(Q10 = quantile(value, 0.1),
            Q90 = quantile(value, 0.9)) %>%
  mutate(true_value = as.vector(W_sparse)) %>%
  arrange(true_value) %>%
  mutate(var_id = row_number()) %>%
  mutate(covered = Q10 <= true_value & true_value <= Q90) %>%
  mutate(model = "Non-Sparse")

bind_rows(q_Y_tibble, q_Y_tibble_sparse) %>%
  ggplot(aes(var_id, true_value, color = model)) +
  geom_errorbar(aes(ymin = Q10, ymax = Q90), position = "dodge") +
  geom_point()

```

```{r}
s_nonsparse <- extract(fit_non_sparse)
s <- extract(fit)

q_Y_tibble_rows_and_cols_sparse <-
  s$Y_mirrored %>%
  melt() %>%
  as_tibble %>%
  set_names(c("sample_id", "row_id", "col_id", "value")) %>%
  group_by(row_id, col_id) %>%
  summarize(Q10 = quantile(value, 0.1),
            Q90 = quantile(value, 0.9)) %>%
  ungroup() %>%
  inner_join(set_names(melt(W_sparse), c("row_id", "col_id", "true_value"))) %>%
  mutate(model = "Sparse")

q_Y_tibble_rows_and_cols_non_sparse <-
  s_nonsparse$Y_mirrored %>%
  melt() %>%
  as_tibble %>%
  set_names(c("sample_id", "row_id", "col_id", "value")) %>%
  group_by(row_id, col_id) %>%
  summarize(Q10 = quantile(value, 0.1),
            Q90 = quantile(value, 0.9)) %>%
  ungroup() %>%
  inner_join(set_names(melt(W_sparse), c("row_id", "col_id", "true_value"))) %>%
  mutate(model = "Non-Sparse")

bind_rows(q_Y_tibble_rows_and_cols_sparse,
          q_Y_tibble_rows_and_cols_non_sparse) %>%
  mutate(row_id = factor(row_id, levels = as.character(50:1))) %>%
  ggplot(aes(true_value, row_id, color = model)) +
  geom_errorbarh(aes(xmin = Q10, xmax = Q90),
                 position=ggstance::position_dodgev(height=0.5)) +
  geom_point() +
  facet_grid(. ~ col_id) +
  scale_color_manual(values=c("black","darkorange")) +
  theme_bw() +
  theme(text = element_text(size=20)) +
  xlab("W") +
  ylab("Row")
```


