---
title: "Uncertainty Quantification of PCA"
output: html_notebook
---

```{r load}
library(tidyverse)
library(rstan)

source("../../Givens.R")
source("../../GenerateSynthetic.R")
```

# Generate Synthetic 3D Data that lies on a 2D plane

```{r}

n <- 3
p <- 2
d <- n*p-p*(p+1)/2

W <- InverseGivensTransform(rep(0.0, d), n, p)

N <- 1000
TwoSeventy <- GenerateHighDimData(n = n, p = p, W = W, LambdaVec = c(100, 50, 10), sd = 1.0, N = N)
ThreeTwo <- GenerateHighDimData(n = 3, p = 2, W = W, LambdaVec = c(5, 4), sd = 1.0, N = N)
EigenNetwork <- GenerateHighDimData(n = n, p = p, W = W, LambdaVec = c(120, 100, 80), sd = 1.0, N = N)

#x <- ThreeTwo$x %>% tbl_df
#save(x, file = "experiments/uncertaintyQuantification/unstableEstimate.Rdata")
load(file = "unstableEstimate.Rdata")

W_hat <- princomp(x)$loadings
source("../../Plotting.R")
points_hat <- GetSurfacePoints(x$V1, x$V2, W_hat[,1:2])

plot_ly(x, x = ~V1, y = ~V2, z = ~V3) %>% add_markers() %>%
  add_surface(x = ~points_hat$x, y = ~points_hat$y, z = ~points_hat$z, opacity = 0.98, colorscale = list("black", "orange"))

points_true <- GetSurfacePoints(x$V1, x$V2, W)

plot_ly(showscale = FALSE) %>%
  add_surface(x = ~points_hat$x, y = ~points_hat$y, z = ~points_hat$z, opacity = 0.98) %>%
  add_surface(x = ~points_true$x, y = ~points_true$y, z = ~points_true$z)
```

Because of small amount of data and low signal to noise ratio, maxmimum likelihood estimate is bad. Lambda values are `r princomp(x)$sdev` and would lead us to believe data is two dimensional, but we would pick the wrong subspace with maximum likelihood.

```{r, message=FALSE}
library(rstan)
sigmaSqHyperPrior <- 10
xMat <- as.matrix(x[,1:3])
SigmaHat <- (1/N)*t(xMat) %*% xMat

dat <- list(N = n, P = p, num_obs = N, SigmaHat = SigmaHat, sigmaSqHyperPrior = sigmaSqHyperPrior)

fit <- stan(file = "../../Stan/ppca_optimized.stan", data = dat, chains = 1, iter = 1)

xMat <- as.matrix(TwoSeventy$x)
SigmaHat <- (1/N)*t(xMat) %*% xMat
dat <- list(N = n, P = p, num_obs = N, SigmaHat = SigmaHat, sigmaSqHyperPrior = sigmaSqHyperPrior)
fit <- stan(file = "../../Stan/ppca_optimized.stan", data = dat, chains = 1, iter = 1)


xMat <- as.matrix(ThreeTwo$x)
SigmaHat <- (1/N)*t(xMat) %*% xMat

xMat <- as.matrix(EigenNetwork$x)
SigmaHat <- (1/N)*t(xMat) %*% xMat
data <- list(n = n, p = p, d = d, sigmaSqHyperPrior = sigmaSqHyperPrior, N = N, SigmaHat = SigmaHat)

expec_Y <- pnorm((W %*% diag(c(3.0, 2.0, 1.0)) %*% t(W)) + 0.1)
Y <- rbinom(n*n, 1, as.vector(expec_Y))

data <- list(n = n, p = p, d = d, sigmaSqHyperPrior = sigmaSqHyperPrior, N = N, Y = Y)
#fit <- stan(file = "../../Stan/StiefelPpca.stan", data = data, chains = 1, iter = 1, init = list(list(theta = c(0,0,0))))

fit <- stan(file = "../../Stan/StiefelPpca.stan", data = data, chains = 1, iter = 1, init = list(list(theta = array(rep(0.0, d)))))

fit <- stan(file = "Stan/StiefelPpca_optimized.stan", data = data, chains = 1, iter = 1, refresh = 1, init = list(list(theta = array(rep(0.0, d)))))
```

```{r}
fit <- stan(file = "../../Stan/fruit_loop.stan", chains = 1, iter = 200000)
```


```{r}
model = stan_model("../../Stan/StiefelPpca_optimized.stan", model_name = "external", allow_undefined = TRUE,
                  includes = paste0('\n#include "', 
                                    file.path(getwd(), '../../Stan/get_time.hpp'), '"\n'))

sampling(model, iter = 1, chains = 1, control = list(max_treedepth = 0))
```


```{r}
library(tidyr)
save(fit, file = "synthFit.Rdata")
s <- rstan::extract(fit)
lambda_posterior <- tibble(Lambda1 = s$lambdaReversed[,3], Lambda2 = s$lambdaReversed[,2], Lambda3 = s$lambdaReversed[,1]) %>%
  gather(Parameter, Sample)

cbPalette <- c("grey45","black","darkorange")

lambda_posterior %>%
  ggplot() +
  geom_histogram(aes(x = Sample, group = Parameter, fill = Parameter), alpha = 0.4, position = "identity", binwidth = 0.05) +
  scale_fill_manual(values=cbPalette) +
  xlim(0,3) +
  geom_vline(xintercept = 1.52, color = "grey45", alpha = 1, size = 1.0) +
  geom_vline(xintercept = 1.27, color = "black", alpha = 1, size = 1.0) +
  geom_vline(xintercept = 0.77, color = "darkorange", alpha = 1, size = 1.0) +
  xlab("Singular Values") +
  ylab("Posterior Sample Counts") +
  theme(text = element_text(size=14))# +
  #facet_grid(Parameter ~.)
```

```{r}
angle_samples <- tibble(GT = s$theta[1:9999,3], EMHMC = byrne_angles$X3*pi/2) %>%
  gather(Method, theta)

cbPalette <- c("black","darkorange")

angle_samples %>%
  ggplot(aes(x = theta, group = Method, fill = Method)) +
  geom_histogram(alpha = 0.4, position = "identity", binwidth = 0.05) +
  scale_fill_manual(values=cbPalette) +
  xlab(expression(theta[2*3])) +
  ylab("Posterior Sample Counts") +
  theme(text = element_text(size=14))
```


```{r}
GivensTransform(W_hat[,1:2])
s <- extract(fit)
qplot(s$theta[,1]/pi)
qplot(s$theta[,2]/pi)
```
